### ISSUE TITLE
All extensions should have a machine readable source of truth

### ISSUE THREAD

**Issue by doug-q** [CQCL/hugr#1228]
We need to be able to exchange extension definitions between different hugr tools. 

All extension documentation should be generated by loading the extension and `.print_docs_markdown()`ing it.

Extensions are already serialisable, with the caveat of #1057 
YAML Declarative extensions are one source of machine readable extensions, but not the only one. Extensions should be exchanged in JSON and validated against a versioned schema, just like Hugrs.

Tasks:
 - [ ] #1057 
 - [x] Define a JSON schema for extensions
 - [ ] Remove all extension docs from the spec and replace with markdown generated by extension definitions.
 - [ ] Guppy is able to load an Extension from JSON and automagically provide the ops and types
