### ISSUE TITLE
Tracking: CFG Structuring

### ISSUE THREAD

**Issue by acl-cqc** [CQCL/hugr#1392]
Believe this is the order to perform stages in, not necessarily to write them:
- [X] Merge Basic Blocks
- [ ] Elide empty BB's (like merging, but edges to an empty BB can be retargetted to its successor *even if the successor has other predecessors*) - probably the same step as previous
- [X] Detect nested regions via Program Structure Tree (done, in `hugr_passes/src/nest_cfgs.rs`) and turn into nested CFG nodes
   - [] Consider extending to "unmerge"/unelide basic blocks (via dominator analysis?): even if we don't merge/elide BBs ourselves, we cannot rely on any input CFG not having been merged/elided already, so ideally we should both merge/elide to normalize, and cope with that
   - Other possible approaches?
      - [Perfect Reconstructability of Control Flow from Demand Dependence Graphs](https://research.google.com/pubs/archive/43246.pdf) suggests (1) identify SCCs (2) for each SCC, introduce a single entry node and single exit node (w/ extra branches/predicates) if there are multiple in/out-edges to distinct targets; each (3) for remaining/acyclic parts, proceed by taking initial dominating (branch) node $B$, subtrees dominated by each out-edge of $B$, and "tail" = the rest; transform "the rest" to have a single entry node by adding extra branches; then recurse on the rest. **These extra branches+predicates will be expensive given our simply-nested conditionals** but do allow handling of things like loops with multiple exits.
      - Decompilation techniques e.g. [Schwartz et al](https://www.usenix.org/conference/usenixsecurity13/technical-sessions/presentation/schwartz) seem to work by a simpler mechanism of fitting "templates" (branch/loop), this doesn't seem as principled/well-structured, but they have examples of e.g. multiple-exit loops that our PST technique doesn't handle. (That paper also has a useful-for-decompilation technique of turning extra edges into "goto" and then structuring the rest, but this doesn't seem relevant for us.)
      - **Some** insertion of extra predicates + branch nodes is going to allow finding more structure than if we don't, albeit at extra runtime cost. ATM we think this is not important, *e.g.* we do not expect a guppy loop to become a Hugr TailLoop if it contains `break` or `continue`
- [ ] #945 - could be before or after:
- [ ] #818

**Comment by acl-cqc** [comment]
Closing here as this everything is now part of https://github.com/Quantinuum/tket2/issues/1799 and discussion probably belongs in the tket2 repo.
