### ISSUE TITLE
Tracking issue for extension requirement inference

### ISSUE THREAD

**Issue by croyzor** [CQCL/hugr#426]
- [x] #1734
- [ ] Feature flag is causing trouble, because of automatic "union" (across all dependencies on the same crate) of feature flags. CONSIDER removing flag (-> always on) straightaway, and updating clients to use `validate_no_extensions` when they don't want it. This may involve changing e.g. `ValidationLevel`.
    - [ ] Changing `validate()` and `validate_no_extensions()` to `validate(bool)` is a syntactic difference only but we can CONSIDER that too. 
- [ ] Turn feature flag on in all clients - https://github.com/CQCL/tket2/issues/688
- [ ] Optionally, if needed, #1237. NOTE there is no penalty for this except extra code (and cost at *inference*-time for clients that do *inference* - it does not affect validation)
- [ ] Update spec
- [ ] Remove feature flag (always on)
- [ ] We'll also want #709 at some point

----
Completed steps ---- (of new plan following Re^n-super-redux proposed by Lukas:
- [x] Ignore input_extensions and (non-hierarchy) edges, validate only that extension *deltas* on nodes are a subset of their *parent* - this is #1142
- phase 2:
- [x] Cleanup: remove `input_extensions` and `NodeType` - this is #1183 
- [x] #388
- [x] #640 (this becomes even *more* important than under the `input_extensions`-based scheme because we don't have the "empty delta so inputs = outputs" escape hatch)
- [X] builder front-end for building DFGs (`dfg_builder`): in #1219 (`DFGBuilder::new` takes a FunctionType so no need to update)
- [X] `conditional_builder`, (`simple_`)`block_builder` / `entry_builder` - in #1226
- [x] #1318
--------
Below relates to the "Reredux" where we retain `input_extensions` but switch to only subset constraints between them (effectively, every edge gains a lift node, with the delta of the lift being inferred) - detailed in https://cqc.atlassian.net/wiki/spaces/~221321769/pages/2803236998/HUGR+Extension+Inference+reredux. 

Redux Plan:
- [x] #943 (Preliminary to 713 and 918)
- [x] #713
- [x] #457 
- [x] #918 
- [ ] #919 
- [x] #745 

At this point, the following issues can be dropped (and `Lift` nodes removed):
- #423 
- #819

And these should become easy: 
- #695 
- #388 

At which point we hopefully should find the system is usable enough to turn inference back on (no more feature gate)

Then we should revisit
- #702 
- #709 

Finally, we hope this last step is an "optional extra" / improvement, rather than part of the MVP:
 - [x] #640

**Comment by acl-cqc** [comment]
A few suggestions...
* Can we make lift nodes, and `Plus` constraints, take an ExtensionSet rather than a single Extension?
* ....and then, can we make Lift nodes *not specify* the ExtensionSet, and get inference to figure it out?

Even that might be a lesser step than #423, but I'm wondering how easy that will be

We might want to work on error reporting. Picking out a random (HashSet-iteration-order) location (i.e. `(Node,Direction)`) for each Meta (in `report_mismatch`) isn't terribly helpful.
